### ISSUE TITLE
picture with bulgarian text

### ISSUE THREAD

**Issue by BGdaredevil** [SoftUni/Programming-Basics-Book-JS-EN#1]

**Comment by BGdaredevil** [comment]
> ## Link https://github.com/SoftUni/Programming-Basics-Book-JS-EN/edit/master/chapter-07-complex-loops.md
> ## Description - a pic with Bulgarian text in line 32
> ## Current Text
> ## Corrected Text

Additional BG text picture - line 64

**Comment by nakov** [comment]
Thank for reporting. This book is still unfinished, and the images will be translated to English soon.

**Comment by nakov** [comment]
Fixed
